import { useState } from 'react';
import { 
  useListAiDrafts, 
  useApproveAiDraft, 
  useRejectAiDraft,
  useGenerateAiDraft,
  useCreateAiDraft,
  useListCases,
  getListAiDraftsQueryKey
} from '@workspace/api-client-react';
import { PageHeader } from '@/components/layout/Shell';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader } from '@/components/ui/card';
import { StatusBadge } from '@/components/ui/status-badge';
import { Wand2, Check, X, FileText, CornerDownRight, Loader2 } from 'lucide-react';
import { format } from 'date-fns';
import { useQueryClient } from '@tanstack/react-query';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Label } from '@/components/ui/label';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';

const DRAFT_TYPES = [
  { value: 'contract', label: 'Contract' },
  { value: 'pleading', label: 'Pleading' },
  { value: 'letter', label: 'Letter' },
  { value: 'legal_answer', label: 'Legal Answer' },
  { value: 'other', label: 'Other' },
];

export default function AiDrafts() {
  const queryClient = useQueryClient();
  const [selectedDraftId, setSelectedDraftId] = useState<number | null>(null);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [draftType, setDraftType] = useState<string>('');
  const [caseId, setCaseId] = useState<string>('');
  const [instructions, setInstructions] = useState('');
  const [generateError, setGenerateError] = useState<string | null>(null);

  const { data: drafts, isLoading } = useListAiDrafts({}, { 
    query: { queryKey: getListAiDraftsQueryKey({}) } 
  });

  const { data: cases } = useListCases({});

  const approveDraft = useApproveAiDraft();
  const rejectDraft = useRejectAiDraft();
  const generateDraft = useGenerateAiDraft();
  const createDraft = useCreateAiDraft();

  const isGenerating = generateDraft.isPending || createDraft.isPending;

  const handleApprove = (id: number) => {
    approveDraft.mutate({
      id,
      data: { reviewedById: 1 }
    }, {
      onSuccess: () => {
        queryClient.invalidateQueries({ queryKey: getListAiDraftsQueryKey({}) });
        if (selectedDraftId === id) setSelectedDraftId(null);
      }
    });
  };

  const handleReject = (id: number) => {
    rejectDraft.mutate({
      id,
      data: { reviewedById: 1, reviewNotes: "Rejected from review queue" }
    }, {
      onSuccess: () => {
        queryClient.invalidateQueries({ queryKey: getListAiDraftsQueryKey({}) });
        if (selectedDraftId === id) setSelectedDraftId(null);
      }
    });
  };

  const handleOpenDialog = () => {
    setDraftType('');
    setCaseId('');
    setInstructions('');
    setGenerateError(null);
    setDialogOpen(true);
  };

  const handleGenerate = () => {
    if (!draftType || !instructions.trim()) return;
    setGenerateError(null);

    const body: { draftType: string; instructions: string; caseId?: number } = {
      draftType,
      instructions: instructions.trim(),
    };
    if (caseId && caseId !== 'none') {
      body.caseId = Number(caseId);
    }

    generateDraft.mutate({ data: body }, {
      onSuccess: (generated) => {
        createDraft.mutate({
          data: {
            title: generated.title,
            content: generated.content,
            draftType,
            ...(body.caseId !== undefined ? { caseId: body.caseId } : {}),
            createdById: 1,
          }
        }, {
          onSuccess: (newDraft) => {
            queryClient.invalidateQueries({ queryKey: getListAiDraftsQueryKey({}) });
            setDialogOpen(false);
            setSelectedDraftId(newDraft.id);
          },
          onError: () => {
            setGenerateError('Failed to save draft. Please try again.');
          }
        });
      },
      onError: () => {
        setGenerateError('AI generation failed. Please check your instructions and try again.');
      }
    });
  };

  const selectedDraft = drafts?.find(d => d.id === selectedDraftId);

  return (
    <div className="flex-1 flex flex-col h-screen overflow-hidden">
      <PageHeader 
        title="AI Draft Approvals" 
        description="Review, edit, and approve legal documents generated by AI."
      >
        <Button onClick={handleOpenDialog} className="gap-2">
          <Wand2 className="h-4 w-4" />
          Generate with AI
        </Button>
      </PageHeader>

      <div className="flex-1 flex overflow-hidden">
        {/* List Column */}
        <div className="w-1/3 border-r border-border/40 bg-card overflow-y-auto flex flex-col">
          <div className="p-4 border-b border-border/40 sticky top-0 bg-card z-10">
            <h3 className="font-serif font-bold text-lg mb-4">Pending Review Queue</h3>
            <div className="flex p-1 bg-muted/50 rounded-lg">
              {['pending_approval', 'approved', 'rejected'].map(status => (
                <button
                  key={status}
                  className={`flex-1 px-2 py-1.5 text-xs font-medium rounded-md capitalize transition-colors ${
                    status === 'pending_approval' ? 'bg-card text-foreground shadow-sm' : 'text-muted-foreground hover:text-foreground'
                  }`}
                >
                  {status.replace('_', ' ')}
                </button>
              ))}
            </div>
          </div>
          
          <div className="divide-y divide-border/40 flex-1">
            {isLoading ? (
              [...Array(5)].map((_, i) => (
                <div key={i} className="p-4 bg-card animate-pulse space-y-3">
                  <div className="h-4 bg-muted rounded w-3/4"></div>
                  <div className="h-3 bg-muted rounded w-1/2"></div>
                </div>
              ))
            ) : drafts?.length ? (
              drafts.map(draft => (
                <button
                  key={draft.id}
                  onClick={() => setSelectedDraftId(draft.id)}
                  className={`w-full text-left p-4 transition-colors hover:bg-muted/30 focus:outline-none ${
                    selectedDraftId === draft.id ? 'bg-muted/50 border-l-2 border-l-primary' : 'border-l-2 border-l-transparent'
                  }`}
                >
                  <div className="flex justify-between items-start mb-2">
                    <StatusBadge status={draft.status} className="text-[10px] px-1.5 py-0" />
                    <span className="text-[10px] font-mono text-muted-foreground">{format(new Date(draft.createdAt), 'MMM dd')}</span>
                  </div>
                  <h4 className="font-medium text-sm text-foreground line-clamp-2 mb-1">{draft.title}</h4>
                  <div className="text-xs text-muted-foreground flex items-center gap-1">
                    <span className="uppercase tracking-wider">{draft.draftType.replace('_', ' ')}</span>
                  </div>
                  {draft.caseName && (
                    <div className="mt-2 text-xs text-primary flex items-center gap-1">
                      <CornerDownRight className="h-3 w-3" />
                      <span className="truncate">{draft.caseName}</span>
                    </div>
                  )}
                </button>
              ))
            ) : (
              <div className="p-8 text-center text-muted-foreground">
                <Wand2 className="h-8 w-8 mx-auto mb-3 opacity-20" />
                <p className="text-sm font-medium mb-1">No drafts yet.</p>
                <p className="text-xs">Click "Generate with AI" to create your first draft.</p>
              </div>
            )}
          </div>
        </div>

        {/* Detail Column */}
        <div className="w-2/3 bg-slate-50/50 dark:bg-transparent overflow-y-auto p-8 relative">
          {selectedDraft ? (
            <div className="max-w-3xl mx-auto space-y-6">
              <div className="flex items-start justify-between">
                <div>
                  <div className="flex items-center gap-3 mb-2">
                    <StatusBadge status={selectedDraft.status} />
                    <span className="text-xs text-muted-foreground font-mono">Generated {format(new Date(selectedDraft.createdAt), 'MMM dd, yyyy h:mm a')}</span>
                  </div>
                  <h2 className="text-2xl font-serif font-bold text-foreground">{selectedDraft.title}</h2>
                  <p className="text-sm text-muted-foreground mt-1">
                    Requested by {selectedDraft.createdByName} for {selectedDraft.caseName}
                  </p>
                </div>
                
                {selectedDraft.status === 'pending_approval' && (
                  <div className="flex items-center gap-2">
                    <Button 
                      variant="outline" 
                      className="border-destructive/30 text-destructive hover:bg-destructive/10"
                      onClick={() => handleReject(selectedDraft.id)}
                      disabled={rejectDraft.isPending}
                    >
                      <X className="mr-2 h-4 w-4" /> Reject
                    </Button>
                    <Button 
                      className="bg-emerald-600 hover:bg-emerald-700 text-white"
                      onClick={() => handleApprove(selectedDraft.id)}
                      disabled={approveDraft.isPending}
                    >
                      <Check className="mr-2 h-4 w-4" /> Approve Draft
                    </Button>
                  </div>
                )}
              </div>

              <Card className="border-border/40 shadow-sm overflow-hidden">
                <CardHeader className="bg-card border-b border-border/40 py-3 px-6 flex flex-row items-center justify-between">
                  <div className="flex items-center gap-2 text-sm font-medium">
                    <FileText className="h-4 w-4 text-primary" />
                    Document Preview
                  </div>
                  <Button variant="ghost" size="sm" className="h-8 text-xs font-mono">Edit Mode</Button>
                </CardHeader>
                <CardContent className="p-0">
                  <div className="bg-white dark:bg-slate-900 p-8 min-h-[500px]">
                    <article className="prose prose-sm dark:prose-invert prose-headings:font-serif prose-p:leading-relaxed max-w-none text-slate-800 dark:text-slate-200">
                      {selectedDraft.content.split('\n\n').map((paragraph, i) => (
                        <p key={i}>{paragraph}</p>
                      ))}
                    </article>
                  </div>
                </CardContent>
              </Card>
            </div>
          ) : (
            <div className="absolute inset-0 flex items-center justify-center text-center text-muted-foreground p-8">
              <div className="max-w-md space-y-4">
                <div className="w-16 h-16 rounded-2xl bg-muted flex items-center justify-center mx-auto mb-6">
                  <Wand2 className="h-8 w-8 text-muted-foreground" />
                </div>
                <h3 className="text-xl font-serif font-bold text-foreground">Select a draft to review</h3>
                <p className="text-sm">Review AI-generated legal documents before they are finalized and added to the case file. You can approve, reject, or edit the content directly.</p>
                <Button variant="outline" onClick={handleOpenDialog} className="gap-2 mt-2">
                  <Wand2 className="h-4 w-4" />
                  Generate with AI
                </Button>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Generate Draft Dialog */}
      <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
        <DialogContent className="sm:max-w-[540px]">
          <DialogHeader>
            <DialogTitle className="font-serif text-xl flex items-center gap-2">
              <Wand2 className="h-5 w-5 text-primary" />
              Generate with AI
            </DialogTitle>
            <DialogDescription>
              Describe what you need and the AI will draft a legal document for your review.
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-5 py-2">
            {/* Draft Type */}
            <div className="space-y-2">
              <Label htmlFor="draftType">Document type <span className="text-destructive">*</span></Label>
              <Select value={draftType} onValueChange={setDraftType}>
                <SelectTrigger id="draftType">
                  <SelectValue placeholder="Select a document type…" />
                </SelectTrigger>
                <SelectContent>
                  {DRAFT_TYPES.map(t => (
                    <SelectItem key={t.value} value={t.value}>{t.label}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            {/* Case Picker (optional) */}
            <div className="space-y-2">
              <Label htmlFor="caseId">
                Related case <span className="text-muted-foreground text-xs">(optional)</span>
              </Label>
              <Select value={caseId} onValueChange={setCaseId}>
                <SelectTrigger id="caseId">
                  <SelectValue placeholder="Select a case…" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="none">No case</SelectItem>
                  {cases?.map(c => (
                    <SelectItem key={c.id} value={String(c.id)}>{c.title}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            {/* Instructions */}
            <div className="space-y-2">
              <Label htmlFor="instructions">Instructions <span className="text-destructive">*</span></Label>
              <Textarea
                id="instructions"
                placeholder="Describe what you need in this document — parties involved, key terms, purpose, relevant details…"
                className="min-h-[130px] resize-none"
                value={instructions}
                onChange={e => setInstructions(e.target.value)}
              />
            </div>

            {generateError && (
              <p className="text-sm text-destructive bg-destructive/10 rounded-md px-3 py-2">{generateError}</p>
            )}

            {isGenerating && (
              <div className="flex items-center gap-2 text-sm text-muted-foreground bg-muted/50 rounded-md px-3 py-2">
                <Loader2 className="h-4 w-4 animate-spin text-primary" />
                <span>{generateDraft.isPending ? 'Generating document with AI…' : 'Saving draft…'}</span>
              </div>
            )}
          </div>

          <DialogFooter>
            <Button variant="outline" onClick={() => setDialogOpen(false)} disabled={isGenerating}>
              Cancel
            </Button>
            <Button
              onClick={handleGenerate}
              disabled={!draftType || !instructions.trim() || isGenerating}
              className="gap-2"
            >
              {isGenerating ? (
                <><Loader2 className="h-4 w-4 animate-spin" /> Generating…</>
              ) : (
                <><Wand2 className="h-4 w-4" /> Generate Draft</>
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
